//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Prilozhenie_2
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Справ учен.
    /// </summary>
    // *** Start programmer edit section *** (СправУчен CustomAttributes)

    // *** End programmer edit section *** (СправУчен CustomAttributes)
    [AutoAltered()]
    [Caption("Справ учен")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СправУченE", new string[] {
            "ФИОУченика as \'Ф и о ученика\'",
            "СправКлас as \'Справ клас\'",
            "СправКлас.Классы as \'Классы\'",
            "СправРод as \'Справ род\'",
            "СправРод.ФИОРод as \'Ф и о род\'"}, Hidden=new string[] {
            "СправКлас.Классы",
            "СправРод.ФИОРод"})]
    [MasterViewDefineAttribute("СправУченE", "СправКлас", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Классы")]
    [MasterViewDefineAttribute("СправУченE", "СправРод", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОРод")]
    [View("СправУченL", new string[] {
            "ФИОУченика as \'Ф и о ученика\'",
            "СправКлас.Классы as \'Классы\'",
            "СправРод.ФИОРод as \'Ф и о род\'"})]
    public class СправУчен : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИОУченика;
        
        private IIS.Prilozhenie_2.СправКлас fСправКлас;
        
        private IIS.Prilozhenie_2.СправРод fСправРод;
        
        // *** Start programmer edit section *** (СправУчен CustomMembers)

        // *** End programmer edit section *** (СправУчен CustomMembers)

        
        /// <summary>
        /// ФИОУченика.
        /// </summary>
        // *** Start programmer edit section *** (СправУчен.ФИОУченика CustomAttributes)

        // *** End programmer edit section *** (СправУчен.ФИОУченика CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОУченика
        {
            get
            {
                // *** Start programmer edit section *** (СправУчен.ФИОУченика Get start)

                // *** End programmer edit section *** (СправУчен.ФИОУченика Get start)
                string result = this.fФИОУченика;
                // *** Start programmer edit section *** (СправУчен.ФИОУченика Get end)

                // *** End programmer edit section *** (СправУчен.ФИОУченика Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправУчен.ФИОУченика Set start)

                // *** End programmer edit section *** (СправУчен.ФИОУченика Set start)
                this.fФИОУченика = value;
                // *** Start programmer edit section *** (СправУчен.ФИОУченика Set end)

                // *** End programmer edit section *** (СправУчен.ФИОУченика Set end)
            }
        }
        
        /// <summary>
        /// Справ учен.
        /// </summary>
        // *** Start programmer edit section *** (СправУчен.СправКлас CustomAttributes)

        // *** End programmer edit section *** (СправУчен.СправКлас CustomAttributes)
        [PropertyStorage(new string[] {
                "СправКлас"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_2.СправКлас СправКлас
        {
            get
            {
                // *** Start programmer edit section *** (СправУчен.СправКлас Get start)

                // *** End programmer edit section *** (СправУчен.СправКлас Get start)
                IIS.Prilozhenie_2.СправКлас result = this.fСправКлас;
                // *** Start programmer edit section *** (СправУчен.СправКлас Get end)

                // *** End programmer edit section *** (СправУчен.СправКлас Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправУчен.СправКлас Set start)

                // *** End programmer edit section *** (СправУчен.СправКлас Set start)
                this.fСправКлас = value;
                // *** Start programmer edit section *** (СправУчен.СправКлас Set end)

                // *** End programmer edit section *** (СправУчен.СправКлас Set end)
            }
        }
        
        /// <summary>
        /// Справ учен.
        /// </summary>
        // *** Start programmer edit section *** (СправУчен.СправРод CustomAttributes)

        // *** End programmer edit section *** (СправУчен.СправРод CustomAttributes)
        [PropertyStorage(new string[] {
                "СправРод"})]
        [NotNull()]
        public virtual IIS.Prilozhenie_2.СправРод СправРод
        {
            get
            {
                // *** Start programmer edit section *** (СправУчен.СправРод Get start)

                // *** End programmer edit section *** (СправУчен.СправРод Get start)
                IIS.Prilozhenie_2.СправРод result = this.fСправРод;
                // *** Start programmer edit section *** (СправУчен.СправРод Get end)

                // *** End programmer edit section *** (СправУчен.СправРод Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (СправУчен.СправРод Set start)

                // *** End programmer edit section *** (СправУчен.СправРод Set start)
                this.fСправРод = value;
                // *** Start programmer edit section *** (СправУчен.СправРод Set end)

                // *** End programmer edit section *** (СправУчен.СправРод Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СправУченE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправУченE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправУченE", typeof(IIS.Prilozhenie_2.СправУчен));
                }
            }
            
            /// <summary>
            /// "СправУченL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СправУченL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СправУченL", typeof(IIS.Prilozhenie_2.СправУчен));
                }
            }
        }
    }
}
